export enum ENTITY_TYPE {
  PRODUCT = 'PRODUCT',
  CATEGORY = 'CATEGORY',
  CUSTOMER = 'CUSTOMER',
  USER = 'USER',
  STORE = 'STORE',
  PACKAGE = 'PACKAGE',
  INVOICE = 'INVOICE',
  ORDER = 'ORDER',
  DELIVERY = 'DELIVERY',
  SHIPPING = 'SHIPPING',
}
