export enum PAYMENT_TYPE {
  CASH = 'CASH',
  CARD = 'CARD',
  PAY_ON_DELIVERY = 'PAY_ON_DELIVERY',
  PAY_ON_DONE = 'PAY_ON_DONE',
  CREDIT_CARD = 'CREDIT_CARD',
  DEBIT_CARD = 'DEBIT_CARD',
  PAYPAL = 'PAYPAL',
  APPLE_PAY = 'APPLE_PAY',
  GOOGLE_PAY = 'GOOGLE_PAY',
  POS = 'POS',
  TYRO = 'TYRO',
  VA = 'VA',
  WECHAT_PAY = 'WECHAT_PAY',
  ALI_PAY = 'ALI_PAY',
  WALLET = 'WALLET',
  ZALO_PAY = 'ZALO_PAY',
  VIET_QR = 'VIET_QR',
  BALANCE = 'BALANCE',
  TRANSFER = 'TRANSFER',
  AFTER_PAY = 'AFTER_PAY',
  ZIP = 'ZIP',
  PAY_ID = 'PAY_ID',
}

export enum PAYMENT_RESOURCE {
  NORMAL = 'NORMAL',
  STORE_ORDER = 'STORE_ORDER',
  CUSTOMER_ORDER = 'CUSTOMER_ORDER',
  CUSTOMER_BOOKING = 'CUSTOMER_BOOKING',
  STORE_BOOKING = 'STORE_BOOKING',
  BALANCE = 'BALANCE',
  PACKAGE = 'PACKAGE',
  INVOICE = 'INVOICE',
  STORE_PAYMENT = 'STORE_PAYMENT',
  STORE_BANK_TRANSFER = 'STORE_BANK_TRANSFER',
}

export enum PAYOUT_RESOURCE {
  STORE = 'store',
}

export enum REFUND_RESOURCE {
  STORE_ORDER = 'STORE_ORDER',
  CUSTOMER_ORDER = 'CUSTOMER_ORDER',
  CUSTOMER_BOOKING = 'CUSTOMER_BOOKING',
  STORE_BOOKING = 'STORE_BOOKING',
}

export enum PAYMENT_PROVIDER {
  AIR_WALLEX = 'AIR_WALLEX',
  STRIPE = 'STRIPE',
  TYRO = 'TYRO',
  PAY_ME = 'PAY_ME',
  HELLO_ZAI = 'HELLO_ZAI',
  FNM = 'FNM',
}
