export enum DIRECT_TYPE {
  VN_AU = 'VN-AU',
  AU_VN = 'AU-VN',
  VN_VN = 'VN-VN',
  AU_AU = 'AU-AU',
}
export enum SHIPPING_STATUS {
  TERMINATED = -1,
  INACTIVE = 0,
  ACTIVE = 1,
  INITIALIZED = 2,
  CONFIRMED = 3,
  REJECTED = 4,
  WAITING_TO_RECEIVE_PACKAGES = 5,
  RECEIVED_PACKAGES = 6,
  CHECKING_PACKAGES = 7,
  PACKING_PACKAGES = 8,
  PACKED = 9,
  UNREAD = 10,
  READ = 11,
  PICKED_PACKAGES = 12,
  TRANSIT = 13,
  PAID = 14,
  SENDING_TO_AIRPORT = 15,
  SENT_TO_AIRPORT = 16,
  INTERNATIONAL_DELIVERING = 17,
  PROCESSING_CUSTOMS_CLEARANCE = 18,
  CUSTOMS_CLEARANCE_DONE = 19,
  DELIVERING_TO_HUB_STATION = 20,
  CREATED_SHIPMENT = 21,
  DELIVERED = 22,
  IN_QUEUED = 23,
  DELIVERING = 24,
  PICKING_PACKAGES = 25,
}

export enum SERVICE_TYPE {
  STANDARD = 'STANDARD',
  PRIORITY = 'PRIORITY',
  COLLECTION = 'COLLECTION',
}

export enum DELIVERY_TYPE {
  PICKUP = 'PICKUP',
  DELIVERY = 'DELIVERY',
  DROP_OFFS = 'DROP_OFFS',
}

export enum COUNTRY {
  VN = 'VN',
  AU = 'AU',
}

export enum GET_VALUE_SETTING_TYPE {
  JSON = 'JSON',
  STRING = 'STRING',
}

export enum SETTING_TYPE {
  PRIVATE = 'PRIVATE',
  PUBLIC = 'PUBLIC',
}
