export enum BUSINESS_TYPE {
  RESTAURANT = 'RESTAURANT',
  CONVENIENCE = 'CONVENIENCE',
  GROCERY = 'GROCERY',
  SPECIALTY_FOOD = 'SPECIALTY_FOOD',
  LIQUOR = 'LIQUOR',
  FLORIST = 'FLORIST',
  PHARMACY = 'PHARMACY',
  RETAIL = 'RETAIL',
  FULFILLMENT = 'FULFILLMENT',
}
