export enum BUSINESS_TYPE {
  RESTAURANT = 'RESTAURANT',
  CONVENIENCE_STORE = 'CONVENIENCE_STORE',
  GROCERY_STORE = 'GROCERY_STORE',
  SPECIALTY_FOOD_STORE = 'SPECIALTY_FOOD_STORE',
  LIQUOR_STORE = 'LIQUOR_STORE',
  FLORIST = 'FLORIST',
  PHARMACY = 'PHARMACY',
  RETAIL = 'RETAIL',
  FULFILLMENT = 'FULFILLMENT',
}
