export enum DOOR_DASH_STATUS {
  DASHER_CONFIRMED = 'DASHER_CONFIRMED',
  DASHER_CONFIRMED_PICKUP_ARRIVAL = 'DASHER_CONFIRMED_PICKUP_ARRIVAL',
  DASHER_PICKED_UP = 'DASHER_PICKED_UP',
  DASHER_CONFIRMED_DROPOFF_ARRIVAL = 'DASHER_CONFIRMED_DROPOFF_ARRIVAL',
  DASHER_DROPPED_OFF = 'DASHER_DROPPED_OFF',
  DELIVERY_CANCELLED = 'DELIVERY_CANCELLED',
  DELIVERY_RETURN_INITIALIZED = 'DELIVERY_RETURN_INITIALIZED',
  DASHER_CONFIRMED_RETURN_ARRIVAL = 'DASHER_CONFIRMED_RETURN_ARRIVAL',
  DELIVERY_RETURNED = 'DELIVERY_RETURNED',
}
