export enum SHIP_DAY_STATUS {
  NOT_ASSIGNED = 'NOT_ASSIGNED',
  NOT_ACCEPTED = 'NOT_ACCEPTED',
  NOT_STARTED_YET = 'NOT_STARTED_YET',
  STARTED = 'STARTED',
  PICKED_UP = 'PICKED_UP',
  READY_TO_DELIVER = 'READY_TO_DELIVER',
  ALREADY_DELIVERED = 'ALREADY_DELIVERED',
  INCOMPLETE = 'INCOMPLETE',
  FAILED_DELIVERY = 'FAILED_DELIVERY',
}
