export enum PROMOTION_TYPE {
  ORDER_AMOUNT = 'ORDER_AMOUNT',
  PRODUCT_AMOUNT = 'PRODUCT_AMOUNT',
  SHIPPING_FEE = 'SHIPPING_FEE',
  BUY_X_GET_Y = 'BUY_X_GET_Y',
}

export enum PROMOTION_CODE_TYPE {
  FIXED_AMOUNT = 'FIXED_AMOUNT',
  PERCENTAGE = 'PERCENTAGE',
}
