export enum PROMOTION_TYPE {
  ORDER_AMOUNT = 'ORDER_AMOUNT',
  PRODUCT_AMOUNT = 'PRODUCT_AMOUNT',
  SHIPPING_FEE = 'SHIPPING_FEE',
  BUY_X_GET_Y = 'BUY_X_GET_Y',
}

export enum PROMOTION_DISCOUNT_TYPE {
  FIXED_AMOUNT = 'FIXED_AMOUNT',
  PERCENTAGE = 'PERCENTAGE',
}

export enum PROMOTION_APPLY_TYPE {
  PRODUCTS = 'PRODUCTS',
}

export enum PROMOTION_COUNTRY {
  ALL = 'ALL',
  SELECTED_COUNTRY = 'SELECTED_COUNTRY',
}

export enum PROMOTION_MINIMUM_REQUIREMENT {
  NO_REQUIREMENTS = 'NO_REQUIREMENTS',
  MIN_PURCHASE = 'MIN_PURCHASE',
}
