# name: Node.js Package

# on:
#   push:
#     branches:
#       - master  # Y

# jobs:

#   publish-gpr:
#     # needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 20
#           registry-url: https://npm.pkg.github.com/
#           scope: '@vcsepis'
#       - run: npm ci
#       # - run: npm run build
#       - run: npm publish
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.GIT_PASSWORD }}

name: VCSEPIS Packages

on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    name: Build and deploy new version
    runs-on: 
      - ubuntu-latest
    steps:
      - name: checkout to repository
        uses: actions/checkout@v4
      - name: install and build
        run: npm ci --save-dev typescript
      - name: publish to registry
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@VCS-VN'
      - run: npm run build
      - run: |
          rm -rf src
          rm .eslintrc.js
          rm .prettierrc
          rm nest-cli.json
          rm .gitignore
          rm -rf .github
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_PASSWORD }}