name: VCSEPIS Packages

on:
  push:
    branches:
      - master
jobs:
  changes:
    name: Check files changes
    runs-on: 
      - ubuntu-latest
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
      - uses: actions/checkout@v3
      - uses: tj-actions/branch-names@v6
        id: branch-name
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ steps.branch-name.outputs.current_branch }}
          filters: |
            src:
              - 'src/**'

  bump-version:
    name: Bump version
    needs: [change]
    if: ${{ needs.changes.outputs.src == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout CICD Repository
        uses: actions/checkout@v3
        with:
          repository: "VCS-VN/librarys.git"
          token: ${{ secrets.GIT_PASSWORD }} 
          ref: master

      - name: publish to registry
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@VCS-VN'

      - name: Bump version and create a new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_PASSWORD }}
        run: |
          git config --global user.email "vcs.epis@gmail.com"
          git config --global user.name "github-build"
          npm version patch -m "ci: bump version to %s"
          git push origin HEAD --follow-tags

  build-and-deploy:
    needs: [bump-version]
    name: Build and deploy new version
    runs-on: 
      - ubuntu-latest
    steps:
      - name: checkout to repository
        uses: actions/checkout@v4
      - name: install and build
        run: npm ci --save-dev typescript
      - name: publish to registry
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@VCS-VN'
      - run: npm run build
      - run: |
          rm -rf src
          rm .eslintrc.js
          rm .prettierrc
          rm nest-cli.json
          rm .gitignore
          rm -rf .github
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_PASSWORD }}